
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Durga
 */
public class Format_Details extends javax.swing.JInternalFrame {

    /**
     * Creates new form format
     */
    public Format_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        jComboBox1 = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("EVEN");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("ODD");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "CSE", "ECE", "EEE", "ME", "CE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

              String [] day={"Mon","Tue","Wed","Thr","Fri","Sat"};
              String [] br1={"CSE3","CSE4","CSE5","CSE6","CSE7","CSE8"};//1
              String [] br2={"ECE3","ECE4","ECE5","ECE6","ECE7","ECE8"};//2
              String [] br3={"EEE3","EEE4","EEE5","EEE6","EEE7","EEE8"};//3
              String [] br4={"ME3","ME4","ME5","ME6","ME7","ME8"};//4
              String [] br5={"CE3","CE4","CE5","CE6","CE7","CE8"};//5
             int  l1=day.length;
             int  l2=br1.length;
             int send;
             int selected;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(selected>0)
    {
          if(selected==1)
        format(1,br1);
        else if(selected==2)
            format(1,br2);
        else if(selected==3)
            format(1,br3);
        else if(selected==4)
            format(1,br4);
        else if(selected==5)
            format(1,br5);
    }
    else
        jOptionPane1.showInputDialog(this,"Select any Branch");
    
        /* int i,c,a=1;
        int line=0;
      try
      {
          
          Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          Connection con=DriverManager.getConnection("jdbc:odbc:College");
          Statement stm=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          Statement stm2=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
         
          ResultSet r=stm.executeQuery("Select count(slot_no) from Slot_Details");
         ResultSet r1=stm1.executeQuery("Select count(Branch) from format");
         
         r1.next();
         line=r1.getInt(1);
         
            r.next();
            c=r.getInt(1);
             int dialogButton=4;
             
         if(line>0)
         {
             
           dialogButton=jOptionPane1.showConfirmDialog(null,"Table format Already Created\nDo you want to Change format","Warning",jOptionPane1.YES_NO_OPTION);   
         }
         else
         {
            
             for(i=0;i<c;i++)
             {
              a=a+i;
              stm.executeUpdate("alter table format add slot"+a+" varchar(MAX)");
              a=1;
             }
             insert(1);
             jOptionPane1.showMessageDialog(this,"Table format Successfully Created"); 
         }
        
         
         
                     System.out.println(c+" "+dialogButton);
                    if(dialogButton==jOptionPane1.YES_OPTION)
                     {
                          stm2.executeUpdate("delete from format");
                          for(int j=1;j<=c;j++)
                          stm2.executeUpdate("alter table format drop column slot"+j+"");
             
                         for(i=1;i<=c;i++)
                           {
                               stm.executeUpdate("alter table format add slot"+i+" varchar(MAX)");
                           }
                         insert(1);
                       jOptionPane1.showMessageDialog(this,"Successfully Recreated"); 
                     }
          } 
          catch(Exception e)
         {
          System.out.println(e);
         }*/

    }//GEN-LAST:event_jButton1ActionPerformed

    
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                           
    if(selected>0)
    {
        if(selected==1)
        format(0,br1);
        else if(selected==2)
            format(0,br2);
        else if(selected==3)
            format(0,br3);
        else if(selected==4)
            format(0,br4);
        else if(selected==5)
            format(0,br5);
        
    }
    else
        jOptionPane1.showMessageDialog(this,"Select any Branch");
       
        /*   int i,c,a=1;
        int line=0;

      try
       {
          
          Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          Connection con=DriverManager.getConnection("jdbc:odbc:College");
          Statement stm=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          Statement stm2=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
         
          ResultSet r=stm.executeQuery("Select count(slot_no) from Slot_Details");
         ResultSet r1=stm1.executeQuery("Select count(Branch) from format");
         
         r1.next();
         line=r1.getInt(1);
         
            r.next();
            c=r.getInt(1);
             int dialogButton=4;
             
         if(line>0)
         {
             
           dialogButton=jOptionPane1.showConfirmDialog(null,"Table format Already Created\nDo you want to Change format","Warning",jOptionPane1.YES_NO_OPTION);   
         }
         else
         {
             for(i=0;i<c;i++)
             {
              a=a+i;
              stm.executeUpdate("alter table format add slot"+a+" varchar(MAX)");
              a=1;
             }
             insert(0);
             jOptionPane1.showMessageDialog(this,"Table format Successfully Created"); 
         }
        
         
         
                    if(dialogButton==jOptionPane1.YES_OPTION)
                     {
                          stm2.executeUpdate("delete from format");
                          for(int j=1;j<=c;j++)
                          stm2.executeUpdate("alter table format drop column slot"+j+"");
             
                         for(i=1;i<=c;i++)
                           {
                               stm.executeUpdate("alter table format add slot"+i+" varchar(MAX)");
                           }
                         insert(0);
                       jOptionPane1.showMessageDialog(this,"Successfully Recreated"); 
                     }
          } 
          catch(Exception e)
         {
          System.out.println(e);
         }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      selected=jComboBox1.getSelectedIndex();
       System.out.println(selected);
    }//GEN-LAST:event_jComboBox1ActionPerformed


    
    
    
    
    
     void format(int f,String branch[])
     {
         int i,c,a=1;
        int line=0;

        try
            {
          
             Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
             Connection con=DriverManager.getConnection("jdbc:odbc:College");
            Statement stm=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
              Statement stm2=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
              ResultSet r=stm.executeQuery("Select count(slot_no) from Slot_Details");
                  ResultSet r1=stm1.executeQuery("Select count(Branch) from format");
         
             r1.next();
             line=r1.getInt(1);
         
              r.next();
             c=r.getInt(1);
              int dialogButton=4;
             
            if(line>0)
             {
             
                dialogButton=jOptionPane1.showConfirmDialog(null,"Table format Already Created\nDo you want to Change format","Warning",jOptionPane1.YES_NO_OPTION);   
              }
            else
            {
             for(i=0;i<c;i++)
             {
              a=a+i;
              stm.executeUpdate("alter table format add slot"+a+" varchar(MAX)");
              a=1;
             }
             insert(f,branch);
             jOptionPane1.showMessageDialog(this,"Table format Successfully Created"); 
         }
        
         
         
                    if(dialogButton==jOptionPane1.YES_OPTION)
                     {
                          stm2.executeUpdate("delete from format");
                          for(int j=1;j<=c;j++)
                          stm2.executeUpdate("alter table format drop column slot"+j+"");
             
                         for(i=1;i<=c;i++)
                           {
                               stm.executeUpdate("alter table format add slot"+i+" varchar(MAX)");
                           }
                         insert(f,branch);
                       jOptionPane1.showMessageDialog(this,"Successfully Recreated"); 
                     }
          } 
          catch(Exception e)
         {
          System.out.println(e);
         }
     }
    
    
    /////////////////////////////////////////////////////////////////////////////
     ////////////////////////////////////////////////////////Insert Intended Sem//////////
     void insert(int remainder,String branch[])
      {
          try
                {         
          
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con=DriverManager.getConnection("jdbc:odbc:College");
                    Statement stm=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                      ResultSet r1 =stm.executeQuery("Select * from format");
                     for(int i=0;i<l1;i++)
                     {
                        for(int k=0;k<l2;k++)
                         {
                              r1.moveToInsertRow();
                              int r=k%2;
                              if(r==remainder)
                              {
                                r1.updateString("Day", day[i]);
                                r1.updateString("Branch", branch[k]);
                                r1.insertRow();
                              }
                         }
                    }         
                } 
                catch(Exception e)
                {
                 System.out.println(e);
                }
      }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
