/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.*;
import java.util.Random;

/**
 *
 * @author Durga
 */
public class regenerate extends javax.swing.JFrame {

    /**
     * Creates new form test3
     */
    public regenerate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        op = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regenerate");

        jButton1.setText("REGENERATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEditorPane1.setInheritsPopupMenu(true);
        jEditorPane1.setPreferredSize(new java.awt.Dimension(150, 150));
        jScrollPane1.setViewportView(jEditorPane1);

        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(350, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                        .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
        String [] fac=new String[50];
        String [] sub=new String[50];
        String [] sem=new String[50];
        String [] Type=new String[50];

        int [] lec=new int[50];
        int [] lab=new int[50];
        int [] tut=new int[50];

        String [][] CSE3=new String[50][50];
        String [][] CSE5=new String[50][50];
        String [][] CSE7=new String[50][50];

        String [][] CSEf3=new String[50][50];
        String [][] CSEf5=new String[50][50];
        String [][] CSEf7=new String[50][50];
    
        int line=0;
        int line1=0;
        int remaininglec=0;
        int [] remain=new int[100];
        
             String [] day={"Mon","Tue","Wed","Thr","Fri","Sat"};
             String [] branch=new String[10];
             String[] selbranch=new String[10];
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jScrollPane1.setHorizontalScrollBar(jScrollPane1.createHorizontalScrollBar());    
        call();
    }//GEN-LAST:event_jButton1ActionPerformed

    
  void selectbranch() 
    {
    try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:College");
            Statement stm2=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
           ResultSet rs2=stm2.executeQuery("Select * from format");

            /////////////////////////////////////////
            ////////////////////Define variable to know to which branch we have to make time table////
            ///////////////////////////////////////////////////////////////////////////
            
            int sel=0;
            for(int i=0;i<3;i++)
            {
               rs2.next();
               selbranch[i]=rs2.getString("Branch");
            }
            rs2.close();
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    
}
    
 ///////////////////////////////////////////////////////////////////////////////
    void call()////////////////////////////////I have this in function to call from other frame 
    { 
        String [] start=new String[15];
        String [] end=new  String[15];
        int slotno=0;

        for(int i=0;i<50;i++)
        {
            for(int j=0;j<50;j++)
            {
                CSE3[i][j]="s";
                CSE5[i][j]="s";
                CSE7[i][j]="s";
                CSEf3[i][j]="s";
                CSEf5[i][j]="s";
                CSEf7[i][j]="s";
            }
        }

        int count=0,lp1;

        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:College");
            Statement stm=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          //  Statement stm2=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
            ResultSet rs=stm.executeQuery("Select * from Subject_FacultyAllotment");
            ResultSet rs1=stm1.executeQuery("Select * from Slot_Details");
          // ResultSet rs2=stm2.executeQuery("Select Branch from format");

            /////////////////////////////////////////
            ////////////////////Define variable to know to which branch we have to make time table////
            ///////////////////////////////////////////////////////////////////////////

           selectbranch();
            
           while(rs1.next())
           {
              start[slotno]=rs1.getString("START");
              end[slotno]=rs1.getString("END");
              slotno++;
           }
           stm1.close();
          // rs1.close();
           
            //System.out.println(selbranch[2]);
            
            while(rs.next())
            {
                fac[count]=rs.getString("FACULTY").trim();
                sub[count]=rs.getString("SUBJECT").trim();
                sem[count]=rs.getString("SEM").trim();
                Type[count]=rs.getString("TYPE").trim();
                lec[count]=rs.getInt("L");
                tut[count]=rs.getInt("T");
                lab[count]=rs.getInt("P");
                count++;
            }

            stm.close();
           // rs.close();
            con.close();
            int check;
            int checklab;
           
            //   System.out.println("Total="+count);
            for(int lp=0;lp<count;lp++)
            {
                if(sem[lp].equals(selbranch[0]))/////////////////////////////////////
                {
                    if(Type[lp].trim().equals("Laboratory"))
                    {
                        remaininglec=lab[lp];
                        lab1(lab,lp,sub,fac,CSEf3,CSEf5,CSEf7,CSE3);
                       // update(sub,lp,"R_P");
                        remain[lp]=remaininglec;
                    }
                    else{
                            remaininglec=lec[lp];
                            theory1(lec,lp,sub,fac,CSEf3,CSEf5,CSEf7,CSE3,5,"");
                           // update(sub,lp,"R_L");
                            remain[lp]=remaininglec;
                        }
                    if(tut[lp]>0)
                    {
                        remaininglec=tut[lp];
                        theory1(tut,lp,sub,fac,CSEf3,CSEf5,CSEf7,CSE3,8,"[T]"); 
                       // update(sub,lp,"R_T");
                        remain[lp]=remaininglec;
                    }
                  }//////////////////////////////////////////////////
                
                    else if(sem[lp].equals(selbranch[1]))///////////////////////////////////////////////
                    {
                        if(Type[lp].trim().equals("Laboratory"))
                        {
                            remaininglec=lab[lp];
                            lab1(lab,lp,sub,fac,CSEf5,CSEf3,CSEf7,CSE5);//////lab
                          //  update(sub,lp,"R_P");
                            remain[lp]=remaininglec;
                        }
                        else{
                            remaininglec=lec[lp];
                            theory1(lec,lp,sub,fac,CSEf5,CSEf3,CSEf7,CSE5,5,"");//////lec
                         //   update(sub,lp,"R_L");
                            remain[lp]=remaininglec;
                           }
                        if(tut[lp]>0)///////////tut
                        {
                            remaininglec=tut[lp];
                            theory1(tut,lp,sub,fac,CSEf5,CSEf3,CSEf7,CSE5,8,"[T]");  
                           // update(sub,lp,"R_T");
                            remain[lp]=remaininglec;
                        }
                      } //////////////////////////////////////////////
                    
                 else if(sem[lp].equals(selbranch[2]))
                       {
               
                         if(Type[lp].trim().equals("Laboratory")) //lab 
                        {
                             remaininglec=lab[lp];
                          lab1(lab,lp,sub,fac,CSEf7,CSEf5,CSEf3,CSE7);
                         // update(sub,lp,"R_P");
                          remain[lp]=remaininglec;
                       }
                         else{
                             remaininglec=lec[lp];
                              theory1(lec,lp,sub,fac,CSEf7,CSEf5,CSEf3,CSE7,5,"");
                          //    update(sub,lp,"R_L");
                              remain[lp]=remaininglec;
                            }
                         if(tut[lp]>0)
                         {
                             remaininglec=tut[lp];
                            theory1(tut,lp,sub,fac,CSEf7,CSEf5,CSEf3,CSE7,8,"[T]");
                          //  update(sub,lp,"R_T");
                            remain[lp]=remaininglec;
                         }
                    }
                }

            
            
            
            
          ///////////////////////////////////////////////////////////////////
            //////////DISPLAY IN TEXTEDITOR????????????????????
            ////////////////////////////////////////////
            display( slotno,start,end,CSE3,CSEf3,CSE5,CSEf5,CSE7,CSEf7);

            }
            catch(Exception ex)
            {
                System.out.println("Geklo");
            }

      }
    
    /////////////////////////////////////////////////Update Remaining Lec/Lab//////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     void update(String subject[],int lp,String type)
     {
             try
            {
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con=DriverManager.getConnection("jdbc:odbc:College");
                Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
              
                stm1.executeUpdate("Update Subject_FacultyAllotment set "+type+"="+remaininglec+" where SUBJECT='"+subject[lp]+"'");
                stm1.close();
                con.close();
            }
            catch(Exception e)
                    {
                    System.out.println(e);
                    }
            }
    
    
    
    
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //update();
        createformat();
        try///////////////////////////////////////for Insert Generated data into
         { /////////////////////////////////////////table
              String [] day={"Mon","Tue","Wed","Thr","Fri","Sat"};
              int l1=day.length;

              Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con=DriverManager.getConnection("jdbc:odbc:College");
                 Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                 Statement stm2=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                  ResultSet rs1=stm1.executeQuery("Select count(SLOT_NO) from Slot_Details");
        
             rs1.next();
            int a=rs1.getInt(1);
          
          if(line==0 && line1==0)
          {
           for(int i=0;i<l1;i++)
           {
              for(int  j=0;j<3;j++)
              {
                  for(int k=0;k<a;k++)
                  {
                      int l=k+1;
                      
                      if(j==0)
                   stm2.executeUpdate("Update format set slot"+l+"='"+CSE3[i][k]+" ["+CSEf3[i][k].trim()+"]' where Day='"+day[i]+"' and Branch='"+branch[j]+"'");
                      else if(j==1)
                   stm2.executeUpdate("Update format set slot"+l+"='"+CSE5[i][k]+" ["+CSEf5[i][k].trim()+"]' where Day='"+day[i]+"' and Branch='"+branch[j]+"'");
                      else if(j==2)
                   stm2.executeUpdate("Update format set slot"+l+"='"+CSE7[i][k]+" ["+CSEf7[i][k].trim()+"]' where Day='"+day[i]+"' and Branch='"+branch[j]+"'");
                  }
                
              }
             } 
          op.showMessageDialog(this,"Successfully Saved");
          }
          con.close();
      }
        catch(Exception e)
        {
          System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
//////////////////////////////////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////
             
           /////////////////Using this function to get name of sem to which we have to asign///////////
             //////////////////////////////////////////////////////////////////////////////
             void createformat()  
            {
              try
              {
                  Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                  Connection con=DriverManager.getConnection("jdbc:odbc:College");
                  Statement stm1=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                  ResultSet rs1=stm1.executeQuery("Select Branch from format");
                  //rs1.next();
                  for(int i=0;i<3;i++)
                  {
                    rs1.next();
                    branch[i]=rs1.getString("Branch");
                  }
                  con.close();
              }
              catch(Exception e)
              {
                  System.out.println(e);
              }
            }
              ///////////////////////////////////////////////////////////////////////
              //////////////////////////////////////////////////////////////////////
              
    
   
    void display( int slotno,String start[],String end[],String CSE3[][],String CSEf3[][],String CSE5[][],String CSEf5[][],String CSE7[][],String CSEf7[][])
    {
        
        createformat();
            jEditorPane1.setText("");
             
             jEditorPane1.setText(jEditorPane1.getText()+"_____________________________________________________________________________________________________________________________________________________________________________________________\n");
             jEditorPane1.setText(jEditorPane1.getText()+"\t\t");
             for(int i=0;i<slotno;i++)
            {
                if(i>=4)
                {
                jEditorPane1.setText(jEditorPane1.getText()+"Period"+(i+1)+"\t");   
                }else
                jEditorPane1.setText(jEditorPane1.getText()+"Period"+(i+1)+"\t\t");
                //System.out.println(slotno);
            }
            jEditorPane1.setText(jEditorPane1.getText()+"\n");
             jEditorPane1.setText(jEditorPane1.getText()+"DAY\tBRANCH\t");
            for(int i=0;i<slotno;i++)
            {
                if(i>=4)
                {
                 jEditorPane1.setText(jEditorPane1.getText()+"["+start[i].trim()+"-"+end[i].trim()+"]\t");
                }else
                jEditorPane1.setText(jEditorPane1.getText()+"["+start[i].trim()+"-"+end[i].trim()+"]\t\t");
            }
             jEditorPane1.setText(jEditorPane1.getText()+"\n_____________________________________________________________________________________________________________________________________________________________________________________________");
          
            
            ///////dislpay subject and faculty in ediotr pane
         //   jEditorPane1.setText(jEditorPane1.getText()+"\n");
              for(int i=0;i<6;i++)
                {
                     jEditorPane1.setText(jEditorPane1.getText()+"\n\n");
                  //jEditorPane1.setText(jEditorPane1.getText()+"\t\t");
                    jEditorPane1.setText(jEditorPane1.getText()+day[i]+"\t"+branch[0]+"\t");
                    for(int j=0;j<slotno;j++)////////////////////////////////CSE3
                    {
                        if(j>=4)
                         {
                            jEditorPane1.setText(jEditorPane1.getText()+CSE3[i][j]+"\t");   
                         }else
                        jEditorPane1.setText(jEditorPane1.getText()+CSE3[i][j]+"\t\t");
                    }
                    jEditorPane1.setText(jEditorPane1.getText()+"\n");
                    jEditorPane1.setText(jEditorPane1.getText()+"\t\t");
                    for(int j=0;j<slotno;j++)
                    {
                        if(j>=4)
                         {
                            jEditorPane1.setText(jEditorPane1.getText()+CSEf3[i][j]+"\t");   
                         }else
                        jEditorPane1.setText(jEditorPane1.getText()+"["+CSEf3[i][j].trim()+"]\t\t");
                    }
                    jEditorPane1.setText(jEditorPane1.getText()+"\n\n");/////////////////////
                    
                    
                    
                    
                   // jEditorPane1.setText(jEditorPane1.getText()+"\t\t");
                   
                    
                    jEditorPane1.setText(jEditorPane1.getText()+day[i]+"\t"+branch[1]+"\t");
                    for(int j=0;j<slotno;j++)/////////////////////////////////////CSE5
                    {
                        if(j>=4)
                         {
                            jEditorPane1.setText(jEditorPane1.getText()+CSE5[i][j]+"\t");   
                         }else
                        jEditorPane1.setText(jEditorPane1.getText()+CSE5[i][j]+"\t\t");
                    }
                    jEditorPane1.setText(jEditorPane1.getText()+"\n");
                    jEditorPane1.setText(jEditorPane1.getText()+"\t\t");
                     for(int j=0;j<slotno;j++)
                    {
                        if(j>=4)
                         {
                            jEditorPane1.setText(jEditorPane1.getText()+CSEf5[i][j]+"\t");   
                         }else
                        jEditorPane1.setText(jEditorPane1.getText()+"["+CSEf5[i][j].trim()+"]\t\t");
                    }
                    jEditorPane1.setText(jEditorPane1.getText()+"\n\n");/////////////////////

                    
                  ///////////////////////////////////////////////////////////////////////////////////////
                    jEditorPane1.setText(jEditorPane1.getText()+day[i]+"\t"+branch[2]+"\t");
                    for(int j=0;j<slotno;j++)/////////////////////////////////CSE7
                    {
                        if(j>=4)
                         {
                            jEditorPane1.setText(jEditorPane1.getText()+CSE7[i][j]+"\t");   
                         }else
                        jEditorPane1.setText(jEditorPane1.getText()+CSE7[i][j]+"\t\t");
                    }
                    jEditorPane1.setText(jEditorPane1.getText()+"\n");
                    jEditorPane1.setText(jEditorPane1.getText()+"\t\t");
                     for(int j=0;j<slotno;j++)
                    {
                        if(j>=4)
                         {
                            jEditorPane1.setText(jEditorPane1.getText()+"["+CSEf7[i][j].trim()+"]\t");   
                         }else
                        jEditorPane1.setText(jEditorPane1.getText()+"["+CSEf7[i][j].trim()+"]\t\t");
                    }
                      jEditorPane1.setText(jEditorPane1.getText()+"\n_____________________________________________________________________________________________________________________________________________________________________________________________");
                   /////////////////////////////////////////////////////////////////////////////////////////////////
                }
        } 
        

    
/////////////////////////CHeck Subject is alloted on this day or not//////////////////
     ////////////////////////////////////////////////////////////////////////////////
     int status(String sub[],int lp1,String day[][],int i,int search)//for check suject on that day
       {
           int check=0;
           for(int j=0;j<search;j++)   
                  {
                      if(sub[lp1].equals(day[i][j]))
                          check=1;   
                  }
           return check;
       }
    
     //////////////////////////////////////////ASSIGN LECTURE///////////////////////////
    /////////////////////////////////////////// Main algorithm////////////
    
    
    
    
    
   /////////////////////////////////////////////////////////////////////////////// 
    int cals(String day[][],int j,int lp)
    {
        
        int check=0;
        for(int i=0;i<5;i++)
        {
            if(day[j][i].equals("s"))
                check++;
        }
        int f=0;
        if(j>0)
            f=j-1;
        else
            f=j;
        if(day[f][4].equals(sub[lp]))
            check=0;
        return check;
    }
    
    
    
    
   ////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////Check Lab subject alloted or not///////////////
    ////////////////////////////////////////////////////////////////////////////////////
    int labcheck(String sub[],int lp1,String day[][],int j)
    {
        int check=0;
        for(int i=5;i<7;i++)
        {
            if(sub[lp1]==day[j][i])
                check++;
        }
       // System.out.println("Hello="+i5+" "+sub[lp]+" "+lec[lp]);
     return check;   
    }
    
    ////////////////////////////////CALLED IN LAB ASSIGN
    ///////////////////////////////////////////////////////////
    //////////////////lab check no. of s
    int calslab(String day[][],int j,int lp)
    {
        int check=0;
        for(int i=5;i<7;i++)
        {
            if(day[j][i].equals("s"))
                check++;
        }
        int f=0;
        if(j>0)
            f=j-1;
        else
            f=j;
        if(day[f][4].equals(sub[lp]))
            check=0;
        return check;
    }
    ////////////////////////////////////////////////////
    int lb1,lb2,lb3,lb4,lb5;
    /////////////////////////LAb assign
    void lab1(int lab[],int lp,String sub[],String fac[],String CSEf[][],String other1[][],String other2[][],String CSE[][])    
    {
        int checklab;
        int check1;
        for(
                int i=0;i<lab[lp];i++)
                     {
                       checklab=labcheck(sub,lp,CSE,0);//Monday
                       check1=calslab(CSE,0,lp);
                       if(checklab==0 && check1>0)
                       {
                           assignlab(CSEf,0, other1,other2,sub,lp,CSE,fac);
                       }
                       else
                       {
                           int checklab1;
                           checklab1=calslab(CSE,1,lp);
                          checklab=labcheck(sub,lp,CSE,1);//Tuesdy
                          lb1=checklab1;
                           if(checklab==0 && checklab1>0)
                           {
                           assignlab(CSEf,1, other1,other2,sub,lp,CSE,fac);
                          }
                          else
                          {
                              int checklab2;
                            checklab2=calslab(CSE,2,lp);
                            checklab=labcheck(sub,lp,CSE,2);//Wednesday
                            lb2=checklab2;
                            if(checklab==0 && checklab2>0)
                            {
                            assignlab(CSEf,2, other1,other2,sub,lp,CSE,fac);
                            }
                            else
                            {
                                int checklab3;
                                checklab3=calslab(CSE,3,lp);
                                checklab=labcheck(sub,lp,CSE,3);//Thursday
                                lb3=checklab3;
                                if(checklab==0 && checklab3>0)
                                {
                                  assignlab(CSEf,3, other1,other2,sub,lp,CSE,fac);
                                }
                                else
                                {
                                    int checklab4;
                                     checklab4=calslab(CSE,4,lp);
                                    checklab=labcheck(sub,lp,CSE,4);//Friday
                                    lb4=checklab4;
                                    if(checklab==0 && checklab4>0)
                                    {
                                     assignlab(CSEf,4, other1,other2,sub,lp,CSE,fac);
                                    }
                                    else
                                    {
                                        int checklab5;
                                        checklab5=calslab(CSE,5,lp);
                                       checklab=labcheck(sub,lp,CSE,5);//Saturday
                                      lb5=checklab5;
                                        if(checklab==0 && checklab5>0)
                                        {
                                         assignlab(CSEf,5, other1, other2,sub,lp,CSE,fac);
                                        } 
                                        else
                                        {
                                         int dialogButton=0;
    dialogButton = op.showConfirmDialog (null, "Too much bunden on "+fac[lp]+"\nDo you want to break contraint for "+fac[lp]+"\nSubject type "+Type[lp]+"\nSubject is "+sub[lp]+"\nRemain Lec/Lab is "+remaininglec,"WARNING", dialogButton);
                                         if(dialogButton==0)
                                            {
                                                int min=0;
                                                if(lb1>0)
                                                    min=1;
                                                else if(lb2>0)
                                                    min=2;
                                                else if(lb3>0)
                                                {
                                                    min=3;  
                                                }
                                                else if(lb4>0)
                                                {
                                                  min=4;  
                                                }
                                                else if(lb5>0)
                                                {
                                                  min=5;
                                                }
                                            Random rn = new Random();
                                            
                                            int ran=rn.nextInt((5 - min) + 1) + min;
                                            assignlabafterbreak(CSEf,ran, other1, other2,sub,lp,CSE,fac);
                                            }
                                         else
                                             remaininglec--;
                                        }
                                        
                                    }
                                }
                            }
                        }
                       } 
                     }
                  }
    
    
    
    
    
    
     //////////////////////////////////////////ASSIGN LAB/////////////////////////
    /////////////////////////////////////////////////
    void assignlab(String insertf[][],int f,String other1[][],String other2[][],String sub[],int lp,String subject[][],String fac[])
    {
         for(int i=5;i<7;i++)
       {

               int com1=other1[f][i].compareTo(fac[lp]);
               int com2=other1[f][i].compareTo(fac[lp]);
           
               if(insertf[f][i]=="s" && com1!=0 && com2!=0)
                {
                   if(i==0)
                   {
                       remaininglec--;
                   insertf[f][i]=fac[lp];
                   subject[f][i]=sub[lp];
                   break;
                  }
               else
               {   
                   int k=i-1; 
                   int com=insertf[f][k].compareTo(fac[lp]);
               
                   if(com!=0)
                   {
                       remaininglec--;
                   insertf[f][i]=fac[lp];
                   subject[f][i]=sub[lp];
                   break;
                   }
               }
             }
       }
    }//////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////
    
    void assignlabafterbreak(String insertf[][],int f,String other1[][],String other2[][],String sub[],int lp,String subject[][],String fac[])
    {
         for(int i=5;i<7;i++)
       {

               int com1=other1[f][i].compareTo(fac[lp]);
               int com2=other1[f][i].compareTo(fac[lp]);
           
               if(insertf[f][i]=="s" && com1!=0 && com2!=0)
                {
                    remaininglec--;
                    insertf[f][i]=fac[lp];
                   subject[f][i]=sub[lp];
                   break;
                }
         }
    }
    ////////////////////////////////////////////////////////////////Theory
    ///////////////////////////////////////////Assign
     int i1,i2,i3,i4,i5,i6;
   void theory1(int lec[],int lp,String sub[],String fac[],String CSEf[][],String other1[][],String other2[][],String CSE[][],int searchno,String s)
    {
      //System.out.println();
        int check;
        int check1;
      for(int i=0;i<lec[lp];i++)
                 {
                     int checki6;
                    check=status(sub,lp,CSE,0,searchno);//Monady
                    checki6=cals(CSE,0,lp);
                    i6=checki6;
                    
                    if(check==0 && checki6>0)
                    {
                        assign(CSEf,0,other1, other2,sub,lp,CSE,fac,s);
                    }
                    else
                    {
                        int checki5;
                        check=status(sub,lp,CSE,1,searchno);//Tuesday
                        checki5=cals(CSE,1,lp);
                        i5=checki5;
                        
                        if(check==0 && checki5>0)
                        {//System.out.println("Hello="+i5+" "+sub[lp]+" "+lec[lp]+"  "+CSE3[1][0]+"  "+CSE3[1][1]+"  "+CSE3[1][2]+"  "+CSE3[1][3]+"  "+CSE3[1][4]+" "+CSEf3[1][4]+" "+CSEf5[1][4]+" "+CSEf7[1][4]);
                          assign(CSEf,1,other1, other2,sub,lp,CSE,fac,s);
                        }
                        else
                        {
                            
                            int checki4;
                            check=status(sub,lp,CSE,2,searchno);//Wednesday
                            checki4=cals(CSE,2,lp);
                            
                            i4=checki4;
                            if(check==0 && checki4>0)
                            {
                              assign(CSEf,2,other1, other2,sub,lp,CSE,fac,s);
                            }
                            else
                            {
                                int check11;
                                check11=cals(CSE,3,lp);
                                check=status(sub,lp,CSE,3,searchno);//Thursday
                                 i1=check11;
                                if(check==0 && check11>0)
                                {
                                  assign(CSEf,3,other1, other2,sub,lp,CSE,fac,s);
                                }
                                else
                                {
                                    int check12=cals(CSE,4,lp);
                                    check=status(sub,lp,CSE,4,searchno);//Friday
                                    i2=check12;
                                    if(check==0 && check12>0)
                                    {
                                     assign(CSEf,4,other1, other2,sub,lp,CSE,fac,s);
                                    }
                                    else
                                    {
                                        int check13;
                                        check13=cals(CSE,5,lp);
                                        check=status(sub,lp,CSE,5,searchno);//Saturday
                                        i3=check13;
                                        if(check==0 && check13>0)
                                        {
                                         assign(CSEf,5,other1, other2,sub,lp,CSE,fac,s);
                                        } 
                                        else
                                        {
                                          //  if(sub[lp]=="JAVA")
                                           // System.out.println("Hello="+i4);
                                            int dialogButton=0;
    dialogButton = op.showConfirmDialog (null, "Too much burdern on "+fac[lp]+"\nDo you want to break contraint for "+fac[lp]+"\nSubject type "+Type[lp]+"\nSubject is "+sub[lp]+"\nRemain Lec/Lab is "+remaininglec,"WARNING", dialogButton);
                                         if(dialogButton==0)
                                            {
                                            int min=0;
                                            if(i6>0)
                                                min=0;
                                            else if(i5>0)
                                                min=1;
                                            else if(i4>0)
                                                min=2;
                                            else if(i1>0)
                                            {
                                             min=3;  
                                            }
                                            else if(i2>0)
                                            {
                                              min=4;  
                                            }
                                            else if(i3>0)
                                            {
                                                min=5;
                                            }
                                            Random rn = new Random();
                                            int ran=rn.nextInt((5 - min) + 1) + min;
                                            assignafterbreakconstraint(CSEf,ran,other1, other2,sub,lp,CSE,fac,s); 
                                            }
                                         else
                                             remaininglec--;
                                        }
                                        
                                    }
                                }
                            }
                        }
                    }    
                 }  
    }
   
   
   
   
   
   
   ////////////////////////////////////ASSIGN LECTURE VITH CONSTRAINT
   
   void assign(String insertf[][],int f,String other1[][],String other2[][],String sub[],int lp,String subject[][],String fac[],String s)
    {
        int j=0,f1;
       for(int i=0;i<5;i++)
       { //System.out.println(sub[lp]+" "+sub[lp]);
           //System.out.println("Hello="+i5+" "+sub[lp]+" "+lec[lp]+"  "+CSE3[1][0]+"  "+CSE3[1][1]+"  "+CSE3[1][2]+"  "+CSE3[1][3]+"  "+CSE3[1][4]+" "+CSEf3[1][4]+" "+CSEf5[1][4]+" "+CSEf7[1][4]);
           int com1=other1[f][i].compareTo(fac[lp]);
           int com2=other2[f][i].compareTo(fac[lp]);
           if(f>0)
           {
              f1=f-1;
           }
           else
               f1=f;
           int com3=sub[lp].compareTo(subject[f1][i]);
           if(insertf[f][i]=="s" && com1!=0 && com2!=0 && com3!=0 )
           {
             
              if(i==0)
                   {
                   insertf[f][i]=fac[lp];
                   subject[f][i]=sub[lp]+s.trim();   
                   remaininglec--;
                   break;
                  }
              else
               {   
                   int k=i-1; 
                   int com=insertf[f][k].compareTo(fac[lp]);
                   if(com!=0)
                   {
                       remaininglec--;
                       insertf[f][i]=fac[lp];
                      subject[f][i]=sub[lp]+s.trim();
                   break;
                   }
               }
            }
               
           }
       }
   
   /////////////////////////////////////////////////
   ////////////////////////////////////////////////Break Constraint  Then assign
    
    void assignafterbreakconstraint(String insertf[][],int f,String other1[][],String other2[][],String sub[],int lp,String subject[][],String fac[],String s)
    {
        int j=0;
       for(int i=0;i<5;i++)
       {
           
           if(insertf[f][i]=="s" && other1[f][i]!=fac[lp] && other2[f][i]!=fac[lp])
           {
               remaininglec--;
                  insertf[f][i]=fac[lp];
                   subject[f][i]=sub[lp]+s.trim();
                   break;                
           }
      }
               
   }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regenerate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regenerate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane op;
    // End of variables declaration//GEN-END:variables
}
