
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import java.awt.*;
import javax.swing.DropMode;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author durga
 */
public class Subject_Allotment extends javax.swing.JInternalFrame {
public int i=0;

  
 /**
     * Creates new form Subject_Allotment
     */
    public Subject_Allotment() {
        initComponents();
    }
    
            DefaultListModel m1=new DefaultListModel();// For
            DefaultListModel m2=new DefaultListModel();
            DefaultListModel m3=new DefaultListModel();
           // DefaultListModel m4=new DefaultListModel();
            //DefaultListModel m5=new DefaultListModel();
          // String  []roomsub={"x","x","x","x","x","x","x","x","x","x"};
         //  String []room=new String[20];
         //  int z=0;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setToolTipText("");
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Select Branch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setPreferredSize(new java.awt.Dimension(6, 25));

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setPreferredSize(new java.awt.Dimension(6, 25));

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setPreferredSize(new java.awt.Dimension(6, 25));

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Allot");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 93, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton4)
                                .addGap(34, 34, 34)
                                .addComponent(jButton5)))
                        .addGap(0, 10, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        jList1.setModel(m1);
        jList2.setModel(m2);
        jList3.setModel(m3);

        m1.clear();
        m2.clear();
        m3.clear();

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

        jComboBox1.removeAllItems();
        try
        {
            String str="SELECT NAME_OF_BRANCH FROM Branch_Details";
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:College");
            Statement stm=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet r=stm.executeQuery(str);
            jComboBox1.addItem("Branch");
            while(r.next())
            {
                jComboBox1.addItem(r.getString("NAME_OF_BRANCH"));
            }
            r.close();
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        jTextField1.setText("");

        if(jComboBox1.getSelectedItem().toString().isEmpty())
        {
            jOptionPane1.showMessageDialog(this," Select Any Branch");
        }

        else
        {
            if(evt.getClickCount()==2)
            {
                jTextField1.setText(jList1.getSelectedValue().toString());
            }

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
       
        if(m1.isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"First Select Branch");
        }
        else if(jTextField1.getText().isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"First Select Faculty");
        }
        else if(m2.isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"There is no Subject Available for ");
        }

        else
        {
            //////////////////////////////////////////////////////////////////////////////////////
            ////////For Show No. of L/T/P
            try
            {
                    String s=jList2.getSelectedValue().toString();
                    String str1="SELECT TYPE_OF_SUBJECT,NO_LECTURE,NO_TUTORIAL,NO_PRACTICAL FROM Subject_Details WHERE NAME_OF_SUBJECT='"+s+"'";
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con1=DriverManager.getConnection("jdbc:odbc:College");
                    Statement stm1=con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet r1=stm1.executeQuery(str1);
                  
                    r1.next();

                    jTextField2.setText(String.valueOf(r1.getInt("NO_LECTURE")));
                    jTextField3.setText(String.valueOf(r1.getInt("NO_TUTORIAL")));
                    jTextField4.setText(String.valueOf(r1.getInt("NO_PRACTICAL")));
                   
                    r1.close();
                    con1.close();

                if(evt.getClickCount()==2)
                {
                    m3.addElement(jList2.getSelectedValue());
                    int i=jList2.getSelectedIndex();
                    m2.removeElementAt(i);
                }

            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            //////////////////////////////////////////////////////////////////////////////////////////////////////////
            ///////////////////////////////////////

        }

    }//GEN-LAST:event_jList2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s=jComboBox1.getSelectedItem().toString().trim();

        if(s.equals("Branch"))
        {
            jOptionPane1.showMessageDialog(this,"Select Branch");
        }
        else
        {
            try
            {

                String str1="SELECT FACULTY_NAME FROM Faculty_Details WHERE FACULTY_BRANCH='"+s+"'";
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con1=DriverManager.getConnection("jdbc:odbc:College");
                Statement stm1=con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet r1=stm1.executeQuery(str1);

                while(r1.next())
                {
                    m1.addElement(r1.getString("FACULTY_NAME"));
                }
                r1.close();
                con1.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            /////////////////////////////////////////////////////////////////////////////////////////////////////
            //////////////////////Take Subject Branch in list2
            try
            {
                
                String str2="SELECT NAME_OF_SUBJECT FROM Subject_Details WHERE BRANCH_OF_SUBJECT='"+s+"'";
                Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                Connection con2=DriverManager.getConnection("jdbc:odbc:College");
                Statement stm2=con2.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet r2=stm2.executeQuery(str2);

                while(r2.next())
                {
                    m2.addElement(r2.getString("NAME_OF_SUBJECT"));
                }
                r2.close();
                con2.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        if(jList1.isSelectionEmpty())
        {
            jOptionPane1.showMessageDialog(this,"Select Faculty First");
        }

        else if(m1.isEmpty() ||  m3.isEmpty() )
        {
            jOptionPane1.showMessageDialog(this,"First Allot Subject ");
        }
        else
        {
            if(evt.getClickCount()==2)
            {
                m2.addElement(jList3.getSelectedValue());
                m3.removeElementAt(jList3.getSelectedIndex());
            }
        }

    }//GEN-LAST:event_jList3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i=0,l=0,t=0,p=0;
        int a=m3.getSize();
        String faculty=jTextField1.getText(),type="";
        String sem="";
        
        if(jList1.isSelectionEmpty())
        {
            jOptionPane1.showMessageDialog(this,"Select Faculty First");
        }

        else if(m1.isEmpty() || m3.isEmpty() )
        {
            jOptionPane1.showMessageDialog(this,"First Allot Subject ");
        }
        else
        {
            for(i=0;i<a;i++)
            {
                String s=m3.getElementAt(i).toString();
                try
                {

                    String str1="SELECT TYPE_OF_SUBJECT,SEMESTER_OF_SUBJECT,NO_LECTURE,NO_TUTORIAL,NO_PRACTICAL FROM Subject_Details WHERE NAME_OF_SUBJECT='"+s+"'";
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con1=DriverManager.getConnection("jdbc:odbc:College");
                    Statement stm1=con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet r1=stm1.executeQuery(str1);
                    r1.next();
                    type=r1.getString("TYPE_OF_SUBJECT");
                    sem=r1.getString("SEMESTER_OF_SUBJECT");
                    l=r1.getInt("NO_LECTURE");
                    t=r1.getInt("NO_TUTORIAL");
                    p=r1.getInt("NO_PRACTICAL");

                    r1.close();
                    con1.close();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                ////////////////////////////////////////////////////////////////////////////////////////////
                //////////////////////////////For Entry in Allotment Table

                try
                {

                    String str2="SELECT * FROM Subject_FacultyAllotment";
                    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
                    Connection con2=DriverManager.getConnection("jdbc:odbc:College");
                    Statement stm2=con2.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                    ResultSet r2=stm2.executeQuery(str2);
                    r2.next();
                    r2.moveToInsertRow();
                    r2.updateString("FACULTY", faculty);
                    r2.updateString("SUBJECT", s);
                    r2.updateString("TYPE", type);
                    r2.updateString("SEM", sem);
                    r2.updateInt("L", l);
                    r2.updateInt("T", t);
                    r2.updateInt("P", p);
                    r2.updateInt("R_L", l);
                    r2.updateInt("R_T", t);
                    r2.updateInt("R_P", p);

                    r2.insertRow();
                    r2.close();
                    con2.close();

                }

                catch(Exception e)
                {
                    System.out.println(e);
                }
                //////////////////////////////////////////////////////////////////////////
            }
            jOptionPane1.showMessageDialog(this,"Subject Alloted to "+faculty);
            m3.clear();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if(jTextField1.getText().isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"Select Faculty");
        }
        else
        {

       jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

        int l=0,t=0,p=0;

        if(m1.isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"First Select Branch");
        }
        else if(jTextField1.getText().isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"First Select Faculty");
        }
        else if(m2.isEmpty())
        {
            jOptionPane1.showMessageDialog(this,"There is no Subject Available for ");
        }
        else if(jList2.isSelectionEmpty())
        {
            jOptionPane1.showMessageDialog(this,"Select Subject ");
        }

        else
        {
            //////////////////////////////////////////////////////////////////////////////////////
            ////////For Show No. of L/T/P
            m3.addElement(jList2.getSelectedValue());
            int i=jList2.getSelectedIndex();
            m2.removeElementAt(i);
            //////////////////////////////////////////////////////////////////////////////////////////////////////////
            ///////////////////////////////////////

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        if(jList1.isSelectionEmpty())
        {
            jOptionPane1.showMessageDialog(this,"Select Faculty First");
        }

        else if(m1.isEmpty() || m3.isEmpty() )
        {
            jOptionPane1.showMessageDialog(this,"First Allot Subject ");
        }
        else if(jList3.isSelectionEmpty())
        {
            jOptionPane1.showMessageDialog(this,"Select Subject ");
        }
        else
        {

            m2.addElement(jList3.getSelectedValue());
            m3.removeElementAt(jList3.getSelectedIndex());

        }
    }//GEN-LAST:event_jButton5ActionPerformed
          

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
